//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.15 at 01:54:50 PM EET 
//


package org.w3.rdf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3.rdf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Label_QNAME = new QName("http://www.w3.org/2000/01/rdf-schema#", "label");
    private final static QName _RDF_QNAME = new QName("http://www.w3.org/1999/02/22-rdf-syntax-ns#", "RDF");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3.rdf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubClassOf }
     * 
     */
    public SubClassOf createSubClassOf() {
        return new SubClassOf();
    }

    /**
     * Create an instance of {@link SubPropertyOf }
     * 
     */
    public SubPropertyOf createSubPropertyOf() {
        return new SubPropertyOf();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link SeeAlso }
     * 
     */
    public SeeAlso createSeeAlso() {
        return new SeeAlso();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link RDF }
     * 
     */
    public RDF createRDF() {
        return new RDF();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/01/rdf-schema#", name = "label")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RDF }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", name = "RDF")
    public JAXBElement<RDF> createRDF(RDF value) {
        return new JAXBElement<RDF>(_RDF_QNAME, RDF.class, null, value);
    }

}
