//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.16 at 04:48:37 PM EEST 
//


package eu.europeana.schemas.ese;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europeana.schemas.ese package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IsShownBy_QNAME = new QName("http://www.europeana.eu/schemas/ese/", "isShownBy");
    private final static QName _Unstored_QNAME = new QName("http://www.europeana.eu/schemas/ese/", "unstored");
    private final static QName _Type_QNAME = new QName("http://www.europeana.eu/schemas/ese/", "type");
    private final static QName _IsShownAt_QNAME = new QName("http://www.europeana.eu/schemas/ese/", "isShownAt");
    private final static QName _Provider_QNAME = new QName("http://www.europeana.eu/schemas/ese/", "provider");
    private final static QName _Object_QNAME = new QName("http://www.europeana.eu/schemas/ese/", "object");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europeana.schemas.ese
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.europeana.eu/schemas/ese/", name = "isShownBy")
    public JAXBElement<String> createIsShownBy(String value) {
        return new JAXBElement<String>(_IsShownBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.europeana.eu/schemas/ese/", name = "unstored")
    public JAXBElement<String> createUnstored(String value) {
        return new JAXBElement<String>(_Unstored_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.europeana.eu/schemas/ese/", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.europeana.eu/schemas/ese/", name = "isShownAt")
    public JAXBElement<String> createIsShownAt(String value) {
        return new JAXBElement<String>(_IsShownAt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.europeana.eu/schemas/ese/", name = "provider")
    public JAXBElement<String> createProvider(String value) {
        return new JAXBElement<String>(_Provider_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.europeana.eu/schemas/ese/", name = "object")
    public JAXBElement<String> createObject(String value) {
        return new JAXBElement<String>(_Object_QNAME, String.class, null, value);
    }

}
